config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #  resources :restaurant
  get "restaurants", to: "restaurants#index"
  post "restaurants", to: "restaurants#create"
  get "restaurants/new", to:"restaurants#new"
  get "restaurants/top", to: "restaurants#top", as: :top_resturants

  get "restaurants/:id/chef", to: "restaurants#chef", as: :chef_restaurant


  post "restaurants/resturant_id/reviews", to: "reviews#create"
  get "restaurants/:id/reviews/new", to: "reviews#new", as: :new_restaurant_review


  get "restaurants/:id", to: "restaurants#show", as: :restaurant

  get"restaurants/:id/edit", to: "restaurants#edit", as: :edit_resturant
  patch "restaurants/:id", to:"restaurants#update"

  delete "restaurants/:id", to: "restaurants#destroy"

  # delete "reviews/:id", to: "reviews#destroy"
  # delete "restaurants", to: "restaurants#destroy_all"

   resources :reviews, only: [:destroy]




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

 def show
  @restaurant = Restaurant.find(params[:id])
end

  def new
      @restaurant = Restaurant.new
  end


  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
    @restaurant =Restaurant.find(params[:id])
    @chef_name = @restaurant.chef_name
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
   @restaurant = Restaurant.find(params[:id])
  end




  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path()
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant = restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  def delete_all
    restaurant_select_all = Restaurant.all
    restaurant_select_all_ids = restaurant_select_all.map {|x| x[:id]}
    restaurant_select_all_ids = restaurant_select_all.destroy(restaurant_select_all_ids)
    redirect_to restaurants_path()
  end


  private


  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
    @review.save
  end

  def create
    @review = Review.new(review_parans)
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @review = Review.find(paramas[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.label :photos %>
  <%= f.file_field :photos %>
  <br>
  <br>
  <br>
  <%= f.submit %>
  <% end %>

app/views/restaurants/chef.html.erb
<h1><%= @restaurant.name  %> s Chef is </h1>
<h3> <%= @chef_name %></h3>
<%= link_to "Back", restaurant_path %>

app/views/restaurants/edit.html.erb
<h2>Edit <strong><%= @restaurant.name %></strong></h2>

<h1> Add your restaurant here</h1>
<div class ="container">
<%= render "form", restaurant: @restaurant %>
</div>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

<div class ="container">
  <ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
  </ul>
  <%= link_to "Create new one", restaurants_new_path %>
</div>

<%# <%= button_to "Delete all", @restaurant, method: :delete%>

app/views/restaurants/new.html.erb
<div class ="title" dysplay-center>
<h1> Add your restaurant here</h1>
</div>

<div class ="container">
<%= render "form", resturant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
 <div class = "container">

 <% @restaurant.id %>
<h2> Welcome to <%= @restaurant.name %>
<p> Rating: <%= "⭐" * @restaurant.rating %></p>
<p> Located in: <%= @restaurant.address %></p>
<%= link_to "See chef", chef_restaurant_path %>
<br>
<br>

<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %></li>
  <% end %>
</ul>
<br>

<li class="list-group-item">
  <%= review.content %>
  <%= link_to "Delete",
    review_path(review),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
</li>


  <%# <%= link_to"add review", review_restaurant_path(@restaurant) %>
  <%# <ul class = "list-group">
    <% @restaurant.review.each do |review| %>
    <%# <li class="list-group-item"><%= review.content %></li>
  <%# <% end %>
<%# </ul> %>
<%# <br> %>

<%# <li class="list-group-item">
  <%= reviews.content %>
  <%# <%= link_to "Delete",
    review_path(review),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
<%# </li> %>

<%= link_to "Back to all resturants", restaurants_path %>

<%= link_to "Edit", edit_resturant_path(@restaurant)%>
<br>
<br>
<%= link_to "Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

</div>

app/views/restaurants/top.html.erb
<h1>5 Stars Restaurants</h1>
<%= render "restaurants/list", restaurants: @restaurants %>
<%= link_to "Back to all restaurants", restaurants_path %>

app/views/reviews/new.html.erb
  <h1>New review</h1>
  <div class ="container">
    <h1>New review</h1>
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
        <%= f.submit "Submit review", class: "btn btn-primary" %>
      <% end %>
  </div>